### ISSUE TITLE
Doesn't do anything

### ISSUE THREAD

**Issue by Drexel14** [DanielHazzard/BurstMaster#1]
So I set this up but when I push run it doesn't do anything.  Also any thoughts on an auto follow system?  That would be helpful for sure.

**Comment by DanielHazzard** [comment]
It's not in a workable state yet.

**Comment by Drexel14** [comment]
Ah, well that explains it doesn't it lol?  Regardless, I did open up the app and view the interface.  Looks like a great project.  I look forward to the working form.
